channels:
  - menpo
  - https://repo.anaconda.com/pkgs/free
  - defaults
  - anaconda
dependencies:
  - apptools=4.4.0
  - asn1crypto=0.24.0
  - backports=1.0
  - backports.functools_lru_cache=1.5
  - backports.shutil_get_terminal_size=1.0.0
  - backports_abc=0.5
  - blas=1.0
  - bokeh=0.13.0
  - ca-certificates=2019.8.28
  - certifi=2019.9.11
  - cffi=1.11.5
  - chardet=3.0.4
  - click=7.0
  - cloudpickle=0.6.1
  - conda=4.7.12
  - conda-package-handling=1.6.0
  - configobj=5.0.6
  - cryptography=2.3.1
  - cycler=0.10.0
  - cytoolz=0.9.0.1
  - dask=0.17.1
  - dask-core=0.17.1
  - decorator=4.3.0
  - distributed=1.21.8
  - docopt=0.6.2
  - enum34=1.1.6
  - envisage=4.7.0
  - freetype=2.9.1
  - functools32=3.2.3.2
  - futures=3.2.0
  - h5py=2.8.0
  - hdf5=1.10.2
  - heapdict=1.0.0
  - idna=2.7
  - imageio=2.4.1
  - intel-openmp=2018.0.3
  - ipaddress=1.0.22
  - ipython=5.8.0
  - ipython_genutils=0.2.0
  - jbig=2.1
  - jinja2=2.10
  - jpeg=9b
  - kiwisolver=1.0.1
  - lcms=1.19
  - libedit=3.1.20170329
  - libffi=3.2.1
  - libpng=1.6.34
  - libtiff=4.0.10
  - linecache2=1.0.0
  - locket=0.2.0
  - markupsafe=1.0
  - matplotlib=2.2.3
  - mayavi=4.5.0
  - mkl=2018.0.3
  - mkl_fft=1.0.4
  - mkl_random=1.0.1
  - mpi4py=2.0.0
  - msgpack-python=0.5.6
  - ncurses=6.1
  - networkx=2.2
  - numexpr=2.6.8
  - numpy=1.11.3
  - numpy-base=1.11.3
  - olefile=0.46
  - opencv=3.4.1
  - openmpi=1.6.3
  - openssl=1.1.1d
  - packaging=18.0
  - pandas=0.23.1
  - partd=0.3.9
  - pathlib2=2.3.2
  - patsy=0.5.0
  - pexpect=4.6.0
  - pickleshare=0.7.4
  - pillow=5.4.1
  - prompt_toolkit=1.0.15
  - psutil=5.4.7
  - ptyprocess=0.6.0
  - pycosat=0.6.3
  - pycparser=2.19
  - pyface=6.0.0
  - pygments=2.2.0
  - pyopenssl=18.0.0
  - pyparsing=2.2.0
  - pyqt=4.11.4
  - pyqtgraph=0.10.0
  - pysocks=1.6.8
  - python=2.7.15
  - python-dateutil=2.7.3
  - pytz=2018.5
  - pywavelets=0.5.2
  - pyyaml=3.13
  - qt=4.8.7
  - readline=7.0
  - requests=2.20.0
  - ruamel_yaml=0.15.46
  - scandir=1.9.0
  - scikit-image=0.13.1
  - scikit-learn=0.19.1
  - scipy=1.1.0
  - seaborn=0.9.0
  - setuptools=40.8.0
  - simplegeneric=0.8.1
  - singledispatch=3.4.0.3
  - sip=4.18
  - six=1.11.0
  - sortedcontainers=2.0.5
  - sqlite=3.25.2
  - statsmodels=0.9.0
  - subprocess32=3.5.2
  - tblib=1.3.2
  - tk=8.6.8
  - toolz=0.9.0
  - tornado=5.1
  - tqdm=4.36.1
  - traceback2=1.4.0
  - traitlets=4.3.2
  - traits=4.6.0
  - traitsui=6.0.0
  - unittest2=1.1.0
  - urllib3=1.23
  - vtk=6.3.0
  - wcwidth=0.1.7
  - wheel=0.33.1
  - xz=5.2.4
  - yaml=0.1.7
  - zict=0.1.3
  - zlib=1.2.11
  - zstd=1.3.7
  - pip:
    - mrcfile==1.0.4
    - pip==18.1

