name: spipy-v3
channels:
  - conda-forge
  - defaults
dependencies:
  - appnope=0.1.0
  - asn1crypto=1.0.1
  - astroid=2.3.1
  - attrs=19.2.0
  - backcall=0.1.0
  - backports=1.0
  - blas=1.0
  - bleach=3.1.0
  - ca-certificates=2019.8.28
  - certifi=2019.9.11
  - cffi=1.12.3
  - chardet=3.0.4
  - conda=4.7.12
  - conda-package-handling=1.6.0
  - configparser=3.7.4
  - cryptography=2.7
  - cycler=0.10.0
  - dbus=1.13.6
  - decorator=4.4.0
  - defusedxml=0.6.0
  - entrypoints=0.3
  - expat=2.2.6
  - freetype=2.9.1
  - gettext=0.19.8.1
  - glib=2.56.2
  - h5py=2.9.0
  - hdf5=1.10.4
  - icu=58.2
  - idna=2.8
  - intel-openmp=2019.4
  - ipykernel=5.1.2
  - ipython=7.8.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.5.1
  - isort=4.3.21
  - jedi=0.15.1
  - jinja2=2.10.3
  - joblib=0.13.2
  - jpeg=9b
  - jsonschema=3.0.2
  - jupyter=1.0.0
  - jupyter_client=5.3.4
  - jupyter_console=6.0.0
  - jupyter_core=4.6.0
  - kiwisolver=1.1.0
  - lazy-object-proxy=1.4.2
  - libcxx=4.0.1
  - libcxxabi=4.0.1
  - libedit=3.1.20181209
  - libffi=3.2.1
  - libgfortran=3.0.1
  - libiconv=1.15
  - libpng=1.6.37
  - libsodium=1.0.16
  - llvm-openmp=4.0.1
  - markupsafe=1.1.1
  - matplotlib=3.1.1
  - mccabe=0.6.1
  - mistune=0.8.4
  - mkl=2019.4
  - mkl-service=2.3.0
  - mkl_fft=1.0.14
  - mkl_random=1.1.0
  - mpi=1.0
  - mpi4py=3.0.2
  - nbconvert=5.6.0
  - nbformat=4.4.0
  - ncurses=6.1
  - notebook=6.0.1
  - numexpr=2.7.0
  - numpy=1.17.2
  - numpy-base=1.17.2
  - openmpi=4.0.1
  - openssl=1.1.1d
  - pandoc=2.2.3.2
  - pandocfilters=1.4.2
  - parso=0.5.1
  - pcre=8.43
  - pexpect=4.7.0
  - pickleshare=0.7.5
  - pip=19.2.3
  - prometheus_client=0.7.1
  - prompt_toolkit=2.0.10
  - psutil=5.6.3
  - ptyprocess=0.6.0
  - pycosat=0.6.3
  - pycparser=2.19
  - pygments=2.4.2
  - pylint=2.4.2
  - pyopenssl=19.0.0
  - pyparsing=2.4.2
  - pyqt=5.9.2
  - pyrsistent=0.15.4
  - pysocks=1.7.1
  - python=3.7.4
  - python-dateutil=2.8.0
  - pytz=2019.3
  - pyzmq=18.1.0
  - qt=5.9.7
  - qtconsole=4.5.5
  - readline=7.0
  - requests=2.22.0
  - ruamel_yaml=0.15.46
  - scikit-learn=0.21.3
  - scipy=1.3.1
  - send2trash=1.5.0
  - setuptools=41.4.0
  - sip=4.19.8
  - six=1.12.0
  - sqlite=3.30.0
  - terminado=0.8.2
  - testpath=0.4.2
  - tk=8.6.8
  - tornado=6.0.3
  - tqdm=4.36.1
  - traitlets=4.3.3
  - urllib3=1.24.2
  - wcwidth=0.1.7
  - webencodings=0.5.1
  - wheel=0.33.6
  - widgetsnbextension=3.5.1
  - wrapt=1.11.2
  - xz=5.2.4
  - yaml=0.1.7
  - zeromq=4.3.1
  - zlib=1.2.11
  - pip:
    - mrcfile==1.1.2

