channels:
  - defaults
  - conda-forge
dependencies:
  - conda=4.8.2
  - python=3.7.4
  - configparser=3.7.4
  - h5py=2.9.0
  - ipython=7.8.0
  - matplotlib=3.1.1
  - mpi4py=3.0.3
  - openmpi=4.0.2
  - numexpr=2.7.0
  - numpy=1.17.2
  - pip=19.2.3
  - psutil=5.6.3
  - qt=5.9.7
  - scikit-learn=0.21.3
  - scipy=1.3.1
  - yaml=0.1.7
  - pyqtgraph=0.10.0
  - pillow=6.2.0
  - pip:
    - mrcfile==1.1.2

